name: Deploy to K3s

on:
  push:
    branches:
      - master  # Trigger deployment when pushing to main branch
  pull_request:
    branches:
      - master  # Trigger deployment on PR to main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up K3s kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.K3S_KUBE_CONFIG }}" > $HOME/.kube/config
        env:
          K3S_KUBE_CONFIG: ${{ secrets.K3S_KUBE_CONFIG }}  # This should be stored as a secret

      - name: Deploy to K3s
        run: |
          kubectl apply -f deploy.yml  # Use kubectl directly
